import mongoose from 'mongoose';

/**
 * ── DermScanReport Schema ───────────────────────────────────────────────────
 * Persists every AI DermScan result generated by a patient.
 *
 * Key design decisions:
 *   • `leadDoctorId` is populated automatically from patient.primaryLeadDoctorId
 *     in the Express controller — patients never set this field manually.
 *   • `deliveryStatus` tracks the full routing lifecycle:
 *       PENDING  → report created, not yet pushed to doctor portal
 *       DELIVERED_TO_LEAD  → Socket.io event fired (or localStorage synced)
 *       REVIEWED  → doctor has opened and acknowledged the report
 *   • `reportData` is a flexible Mixed type so both facial scan and scalp
 *     scan payloads can be stored without separate schemas.
 */
const DermScanReportSchema = new mongoose.Schema(
  {
    // ── Patient who generated the scan ───────────────────────────────────────
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'patientId is required'],
      index: true,
    },

    // ── Lead doctor auto-populated from patient.primaryLeadDoctorId ──────────
    leadDoctorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'leadDoctorId is required — must be auto-populated from patient record'],
      index: true,
    },

    // ── Scan category (drives which report fields are present) ───────────────
    scanType: {
      type: String,
      enum: ['FACIAL', 'SCALP', 'COMBINED'],
      default: 'FACIAL',
      required: true,
    },

    // ── Structured report payload ─────────────────────────────────────────────
    reportData: {
      condition:       { type: String, trim: true },
      confidence:      { type: String, trim: true },   // e.g. "95.4%"
      severity:        { type: String, trim: true },   // "Mild" | "Moderate" | "Severe"
      affectedArea:    { type: String, trim: true },   // e.g. "Malar Cheeks & Chin"
      summary:         { type: String, trim: true },
      recommendations: [{ type: String, trim: true }],
      recommendedRxId: { type: String, default: '' },  // product ID for DermPharmacy
      scanImageUrl:    { type: String, default: '' },  // thumbnail/preview URL
      rawScores: {
        type: mongoose.Schema.Types.Mixed,            // { poreScore, erythemaScore, … }
        default: {},
      },
    },

    // ── Delivery lifecycle ─────────────────────────────────────────────────────
    deliveryStatus: {
      type: String,
      enum: {
        values: ['PENDING', 'DELIVERED_TO_LEAD', 'REVIEWED'],
        message: '{VALUE} is not a valid delivery status',
      },
      default: 'PENDING',
      index: true,
    },

    deliveredAt: { type: Date },   // when the Socket.io / localStorage push happened
    reviewedAt:  { type: Date },   // when the doctor acknowledged

    // ── Optional consultation linkage ─────────────────────────────────────────
    consultationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Consultation',
      default: null,
    },

    // ── Human-readable patient snapshot for doctor's notification tray ────────
    patientSnapshot: {
      fullName: { type: String, default: '' },
      age:      { type: Number, default: 0 },
      gender:   { type: String, default: '' },
    },
  },
  { timestamps: true }
);

// ── Compound indexes for fast doctor-dashboard queries ──────────────────────
DermScanReportSchema.index({ leadDoctorId: 1, deliveryStatus: 1, createdAt: -1 });
DermScanReportSchema.index({ patientId: 1, createdAt: -1 });

const DermScanReport = mongoose.model('DermScanReport', DermScanReportSchema);
export default DermScanReport;
